# Generated by Django 4.2.4 on 2023-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pushed_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_a1c',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_a1c',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_a1c',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_blood_pressure',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_blood_sugar',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_care',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_care',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_default',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_default',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_diary',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_drugs',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_drugs',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_drugs',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_friend',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_friend',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_medical',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_medical',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='created_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='ended_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='started_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_vip',
            name='updated_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='user_weight',
            name='recorded_at',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='validation',
            name='expire_time',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
    ]
