# Generated by Django 4.2.4 on 2023-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_news_created_at_alter_news_pushed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='birthday',
            field=models.DateTimeField(default='1920-1-1 00:00:00', null=True),
        ),
    ]
