# Generated by Django 4.2.4 on 2023-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_data_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='birthday',
            field=models.DateField(default='1920-1-1', null=True),
        ),
    ]
